In [1]:
import numpy as np
import pandas as pd
import requests

In [2]:
url = "https://archive-api.open-meteo.com/v1/archive"

In [3]:
response = requests.get(url)

In [4]:
print(response.status_code)

200

In [5]:
print("Response:", response.text[:500])

Response:

In [6]:
params = {
    "longitude" : 77.5937,
    "latitude" : 12.9719,
    "start_date": "2026-07-01",
    "end_date": "2026-10-08",
    "daily":  ["temperature_2m_mean",
               "temperature_2m_max",
              "temperature_2m_min",
              "precipitation_sum",
              "wind_speed_10m_max"
               ],
    "timezone": "auto"
}

response = requests.get(url, params=params)

print(response.status_code)

200

In [7]:
# Convert json to python data
data = response.json()
print(data["daily"])

{'time': ['2026-07-01', '2026-07-02', '2026-07-03', '2026-07-04', '2026-07-05', '2026-07-06', '2026-07-07', '2026-07-08', '2026-07-09', '2026-07-10', '2026-07-11', '2026-07-12', '2026-07-13', '2026-07-14', '2026-07-15', '2026-07-16', '2026-07-17', '2026-07-18', '2026-07-19', '2026-07-20', '2026-07-21', '2026-07-22', '2026-07-23', '2026-07-24', '2026-07-25', '2026-07-26', '2026-07-27', '2026-07-28', '2026-07-29', '2026-07-30', '2026-07-31', '2026-08-01', '2026-08-02', '2026-08-03', '2026-08-04', '2026-08-05', '2026-08-06', '2026-08-07', '2026-08-08', '2026-08-09', '2026-08-10', '2026-08-11', '2026-08-12', '2026-08-13', '2026-08-14', '2026-08-15', '2026-08-16', '2026-08-17', '2026-08-18', '2026-08-19', '2026-08-20', '2026-08-21', '2026-08-22', '2026-08-23', '2026-08-24', '2026-08-25', '2026-08-26', '2026-08-27', '2026-08-28', '2026-08-29', '2026-08-30', '2026-08-31', '2026-09-01', '2026-09-02', '2026-09-03', '2026-09-04', '2026-09-05', '2026-09-06', '2026-09-07', '2026-09-08', '2026-09-09', '2026-09-10', '2026-09-11', '2026-09-12', '2026-09-13', '2026-09-14', '2026-09-15', '2026-09-16', '2026-09-17', '2026-09-18', '2026-09-19', '2026-09-20', '2026-09-21', '2026-09-22', '2026-09-23', '2026-09-24', '2026-09-25', '2026-09-26', '2026-09-27', '2026-09-28', '2026-09-29', '2026-09-30', '2026-10-01', '2026-10-02', '2026-10-03', '2026-10-04', '2026-10-05', '2026-10-06', '2026-10-07', '2026-10-08'], 'temperature_2m_mean': [22.7, 24.0, 23.7, 23.3, 24.0, 24.3, 24.1, 24.0, 24.6, 24.3, 25.3, 25.6, 25.8, 25.8, 25.4, 25.0, 22.8, 22.8, 23.7, 22.9, 24.0, 22.5, 24.0, 24.0, 23.4, 23.6, 24.4, 24.5, 24.2, 24.0, 24.4, 23.2, 24.3, 23.3, 22.8, 22.8, 22.5, 22.1, 22.9, 23.8, 23.5, 23.8, 23.9, 24.0, 23.9, 24.3, 24.7, 24.2, 24.3, 23.8, 23.4, 23.3, 22.7, 22.9, 22.3, 22.9, 23.6, 23.8, 23.6, 23.1, 23.3, 23.7, 23.9, 24.6, 24.1, 24.7, 25.9, 26.2, 25.9, 25.5, 25.5, 25.8, 26.2, 26.3, 25.4, 25.1, 24.4, 25.5, 25.2, 25.9, 25.7, 23.3, 23.7, 23.7, 23.1, 23.2, 22.7, 23.8, 24.7, 24.0, 23.7, 22.9, 24.4, 24.3, 24.3, 25.4, 23.9, 23.9, 24.3, 24.5], 'temperature_2m_max': [25.8, 28.9, 27.7, 27.6, 28.6, 29.1, 28.6, 28.6, 29.6, 29.9, 30.8, 31.8, 31.8, 32.1, 31.3, 30.8, 27.5, 26.6, 28.4, 28.5, 28.9, 26.6, 29.2, 29.5, 28.9, 27.3, 28.4, 29.7, 29.3, 28.3, 28.9, 27.3, 28.9, 26.1, 28.0, 27.2, 27.3, 27.5, 26.6, 28.3, 28.8, 28.3, 28.7, 28.9, 29.5, 29.3, 30.7, 29.5, 29.9, 28.3, 27.7, 28.6, 27.4, 27.4, 25.8, 27.7, 28.7, 28.8, 28.3, 28.0, 28.8, 28.6, 28.7, 30.2, 28.7, 29.3, 30.8, 30.5, 30.9, 31.0, 30.6, 30.1, 31.0, 30.4, 30.4, 30.4, 30.8, 30.0, 30.5, 30.7, 30.5, 27.2, 29.2, 27.7, 27.1, 29.0, 27.3, 28.2, 29.5, 28.6, 28.1, 28.2, 28.4, 28.8, 29.3, 30.1, 29.4, 28.2, 28.5, 29.2], 'temperature_2m_min': [20.5, 20.8, 21.2, 20.7, 21.1, 20.7, 21.1, 21.1, 21.2, 21.4, 20.4, 20.6, 20.2, 19.9, 19.8, 19.9, 20.9, 20.3, 20.7, 20.6, 20.3, 20.1, 19.6, 19.8, 20.0, 20.3, 20.7, 21.2, 21.6, 21.0, 21.5, 21.2, 21.2, 21.1, 20.5, 20.3, 20.2, 20.6, 20.4, 20.5, 20.0, 20.3, 20.2, 20.9, 20.1, 20.4, 20.4, 20.1, 19.9, 21.2, 20.9, 19.5, 19.5, 20.0, 20.4, 20.6, 20.1, 20.2, 19.9, 19.7, 19.5, 19.3, 19.7, 19.8, 20.1, 20.5, 20.9, 21.4, 20.8, 20.8, 20.4, 21.0, 21.5, 21.8, 20.9, 21.5, 20.4, 20.5, 20.5, 21.5, 21.3, 20.7, 20.7, 20.8, 20.2, 20.0, 21.0, 19.8, 19.6, 21.1, 19.8, 19.5, 21.0, 20.5, 20.1, 20.9, 20.0, 20.5, 20.8, 20.5], 'precipitation_sum': [1.1, 1.2, 2.9, 3.9, 1.2, 1.1, 0.9, 2.3, 0.8, 3.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 9.8, 6.0, 1.0, 8.3, 0.7, 8.9, 1.3, 8.2, 2.9, 3.1, 1.1, 1.9, 3.3, 3.1, 2.6, 17.0, 1.1, 8.9, 18.5, 9.5, 16.5, 16.8, 4.1, 2.0, 5.6, 1.5, 0.6, 5.6, 5.3, 1.1, 0.2, 1.2, 2.8, 6.8, 5.2, 2.0, 3.6, 9.8, 18.2, 6.3, 1.9, 2.0, 1.3, 2.8, 3.2, 1.0, 2.2, 1.8, 3.6, 3.5, 0.0, 1.1, 0.0, 1.6, 5.1, 1.0, 0.7, 0.1, 0.0, 9.1, 9.0, 5.4, 5.8, 2.3, 1.4, 13.9, 7.7, 5.1, 1.3, 1.6, 6.7, 0.2, 0.1, 3.3, 13.5, 14.3, 1.2, 0.0, 0.1, 0.6, 8.3, 6.4, 0.3, 0.4], 'wind_speed_10m_max': [23.5, 24.1, 25.9, 27.9, 29.9, 29.7, 28.8, 25.5, 19.8, 17.2, 17.7, 17.4, 18.2, 15.3, 16.0, 14.8, 20.5, 17.5, 15.3, 19.5, 19.2, 18.8, 19.8, 21.1, 18.2, 19.6, 23.0, 22.7, 24.7, 25.0, 24.6, 19.4, 18.2, 17.0, 16.6, 20.2, 21.1, 18.9, 18.5, 16.4, 15.3, 14.6, 16.4, 18.0, 16.5, 20.0, 21.8, 17.7, 16.2, 17.6, 17.1, 17.4, 22.2, 17.9, 19.0, 19.7, 17.3, 18.9, 18.9, 22.3, 19.8, 19.3, 15.9, 13.6, 16.3, 13.1, 11.4, 12.4, 13.3, 14.9, 14.6, 13.7, 13.1, 9.9, 9.9, 11.1, 12.7, 8.3, 11.7, 13.5, 9.4, 12.6, 15.6, 15.7, 22.4, 23.4, 18.4, 14.8, 8.7, 9.2, 11.6, 14.5, 9.9, 11.1, 12.3, 9.1, 9.0, 10.3, 11.8, 11.5]}

In [8]:
weather_df = pd.DataFrame({
    "date": data["daily"]["time"],
    "temperature_mean": data["daily"]["temperature_2m_mean"],
    "temperature_max": data["daily"]["temperature_2m_max"],
    "temperature_min": data["daily"]["temperature_2m_min"],
    "precipitation_mm": data["daily"]["precipitation_sum"],
    "wind_speed_max": data["daily"]["wind_speed_10m_max"]
})

weather_df["city"] = "Bengaluru"

print(weather_df.head())
print(weather_df.shape)

         date  temperature_mean  temperature_max  temperature_min  \
0  2026-07-01              22.7             25.8             20.5
1  2026-07-02              24.0             28.9             20.8
2  2026-07-03              23.7             27.7             21.2
3  2026-07-04              23.3             27.6             20.7
4  2026-07-05              24.0             28.6             21.1

   precipitation_mm  wind_speed_max       city
0               1.1            23.5  Bengaluru
1               1.2            24.1  Bengaluru
2               2.9            25.9  Bengaluru
3               3.9            27.9  Bengaluru
4               1.2            29.9  Bengaluru
(100, 7)

In [9]:

locations = [
    {"state_ut": "Andhra Pradesh", "city": "Amaravati"},
    {"state_ut": "Arunachal Pradesh", "city": "Itanagar"},
    {"state_ut": "Assam", "city": "Dispur"},
    {"state_ut": "Bihar", "city": "Patna"},
    {"state_ut": "Chhattisgarh", "city": "Raipur"},
    {"state_ut": "Goa", "city": "Panaji"},
    {"state_ut": "Gujarat", "city": "Gandhinagar"},
    {"state_ut": "Haryana", "city": "Chandigarh"},
    {"state_ut": "Himachal Pradesh", "city": "Shimla"},
    {"state_ut": "Jharkhand", "city": "Ranchi"},
    {"state_ut": "Karnataka", "city": "Bengaluru"},
    {"state_ut": "Kerala", "city": "Thiruvananthapuram"},
    {"state_ut": "Madhya Pradesh", "city": "Bhopal"},
    {"state_ut": "Maharashtra", "city": "Mumbai"},
    {"state_ut": "Manipur", "city": "Imphal"},
    {"state_ut": "Meghalaya", "city": "Shillong"},
    {"state_ut": "Mizoram", "city": "Aizawl"},
    {"state_ut": "Nagaland", "city": "Kohima"},
    {"state_ut": "Odisha", "city": "Bhubaneswar"},
    {"state_ut": "Punjab", "city": "Chandigarh"},
    {"state_ut": "Rajasthan", "city": "Jaipur"},
    {"state_ut": "Sikkim", "city": "Gangtok"},
    {"state_ut": "Tamil Nadu", "city": "Chennai"},
    {"state_ut": "Telangana", "city": "Hyderabad"},
    {"state_ut": "Tripura", "city": "Agartala"},
    {"state_ut": "Uttar Pradesh", "city": "Lucknow"},
    {"state_ut": "Uttarakhand", "city": "Dehradun"},
    {"state_ut": "West Bengal", "city": "Kolkata"},
    {"state_ut": "Andaman and Nicobar Islands", "city": "Port Blair"},
    {"state_ut": "Chandigarh", "city": "Chandigarh"},
    {"state_ut": "Dadra and Nagar Haveli and Daman and Diu", "city": "Daman"},
    {"state_ut": "Delhi", "city": "New Delhi"},
    {"state_ut": "Jammu and Kashmir", "city": "Srinagar"},
    {"state_ut": "Ladakh", "city": "Leh"},
    {"state_ut": "Lakshadweep", "city": "Kavaratti"},
    {"state_ut": "Puducherry", "city": "Puducherry"}
]

In [10]:

print("Total locations:", len(locations))
print(locations[10])

Total locations: 36
{'state_ut': 'Karnataka', 'city': 'Bengaluru'}

In [11]:
print(locations[0]["city"])

Amaravati

In [12]:
for i in locations:
  print(i["city"])

Amaravati
Itanagar
Dispur
Patna
Raipur
Panaji
Gandhinagar
Chandigarh
Shimla
Ranchi
Bengaluru
Thiruvananthapuram
Bhopal
Mumbai
Imphal
Shillong
Aizawl
Kohima
Bhubaneswar
Chandigarh
Jaipur
Gangtok
Chennai
Hyderabad
Agartala
Lucknow
Dehradun
Kolkata
Port Blair
Chandigarh
Daman
New Delhi
Srinagar
Leh
Kavaratti
Puducherry

In [13]:
geo_url = "https://geocoding-api.open-meteo.com/v1/search"

city_coordinates = []

for location in locations:
  city = location["city"]

  response = requests.get(geo_url,params={"name": city , "count": 1})

  geo_data = response.json()

  city_record = {
          "state_ut" : location["state_ut"],
          "city" : city,
          "latitude" : geo_data["results"][0]["latitude"],
          "longitude" : geo_data["results"][0]["longitude"]
  }

  city_coordinates.append(city_record)

city_coord = pd.DataFrame(city_coordinates)

In [14]:
print(
    city_coord[
        city_coord["state_ut"].isin(["Haryana", "Punjab", "Chandigarh"])
    ][["state_ut", "city", "latitude", "longitude"]]
)

      state_ut        city  latitude  longitude
7      Haryana  Chandigarh  30.73629    76.7884
19      Punjab  Chandigarh  30.73629    76.7884
29  Chandigarh  Chandigarh  30.73629    76.7884

In [15]:
city_coord.head()
# print(city_coord.shape)

            state_ut       city  latitude  longitude
0     Andhra Pradesh  Amaravati  16.51400   80.51600
1  Arunachal Pradesh   Itanagar  27.08694   93.60987
2              Assam     Dispur  26.13564   91.80069
3              Bihar      Patna  25.59408   85.13563
4       Chhattisgarh     Raipur  21.23333   81.63333

In [16]:
city_coord.iloc[0]["latitude"]

np.float64(16.514)

In [17]:
longitude = city_coord.iloc[0]["longitude"]
latitude = city_coord.iloc[0]["latitude"]
city = city_coord.iloc[0]["city"]

In [18]:
params = {
    "longitude" : longitude,
    "latitude" : latitude,
    "start_date": "2026-07-01",
    "end_date": "2026-10-08",
    "daily":  ["temperature_2m_mean",
               "temperature_2m_max",
              "temperature_2m_min",
              "precipitation_sum",
              "wind_speed_10m_max"
               ],
    "timezone": "auto"
}

weather_response = requests.get(url, params=params)

weather_data = weather_response.json()

In [19]:
print(weather_data.keys())
print(weather_data["daily"].keys())

dict_keys(['latitude', 'longitude', 'generationtime_ms', 'utc_offset_seconds', 'timezone', 'timezone_abbreviation', 'elevation', 'daily_units', 'daily'])
dict_keys(['time', 'temperature_2m_mean', 'temperature_2m_max', 'temperature_2m_min', 'precipitation_sum', 'wind_speed_10m_max'])

In [20]:
weather_df = pd.DataFrame({
    "date": weather_data["daily"]["time"],
    "temperature_mean": weather_data["daily"]["temperature_2m_mean"],
    "temperature_max": weather_data["daily"]["temperature_2m_max"],
    "temperature_min": weather_data["daily"]["temperature_2m_min"],
    "precipitation_mm": weather_data["daily"]["precipitation_sum"],
    "wind_speed_max": weather_data["daily"]["wind_speed_10m_max"]
})

for index, row in city_coord.iterrows():
  city = row["city"]
  longitude = row["longitude"]
  latitude = row["latitude"]

  print(city,latitude,longitude)

weather_df["city"] = city

print(weather_df.head())
print(weather_df.shape)

Amaravati 16.514 80.516
Itanagar 27.08694 93.60987
Dispur 26.13564 91.80069
Patna 25.59408 85.13563
Raipur 21.23333 81.63333
Panaji 14.85289 -90.9715
Gandhinagar 23.21667 72.68333
Chandigarh 30.73629 76.7884
Shimla 31.10442 77.16662
Ranchi 23.34316 85.3094
Bengaluru 12.97194 77.59369
Thiruvananthapuram 8.4855 76.94924
Bhopal 23.25469 77.40289
Mumbai 19.07283 72.88261
Imphal 24.80805 93.9442
Shillong 25.56892 91.88313
Aizawl 23.72894 92.71791
Kohima 25.67467 94.11099
Bhubaneswar 20.27241 85.83385
Chandigarh 30.73629 76.7884
Jaipur 26.91962 75.78781
Gangtok 27.32574 88.61216
Chennai 13.08784 80.27847
Hyderabad 17.38405 78.45636
Agartala 23.83605 91.27939
Lucknow 26.83928 80.92313
Dehradun 30.32443 78.03392
Kolkata 22.56263 88.36304
Port Blair 11.66613 92.74635
Chandigarh 30.73629 76.7884
Daman 20.41431 72.83236
New Delhi 28.62137 77.2148
Srinagar 34.08565 74.80555
Leh 49.49346 0.10785
Kavaratti 10.56688 72.64203
Puducherry 11.93381 79.82979
         date  temperature_mean  temperature_max  temperature_min  \
0  2026-07-01              31.9             34.9             29.7
1  2026-07-02              30.5             34.2             26.3
2  2026-07-03              30.3             33.2             26.8
3  2026-07-04              28.3             30.7             25.5
4  2026-07-05              29.8             33.1             25.7

   precipitation_mm  wind_speed_max        city
0               0.4            25.2  Puducherry
1               3.1            27.2  Puducherry
2               1.4            25.5  Puducherry
3               5.1            23.6  Puducherry
4               0.7            21.7  Puducherry
(100, 7)

In [21]:
url = "https://archive-api.open-meteo.com/v1/archive"

all_weather_data = []

for index, row in city_coord.iterrows():

    city = row["city"]
    latitude = row["latitude"]
    longitude = row["longitude"]

    params = {
        "latitude": latitude,
        "longitude": longitude,
        "start_date": "2026-07-01",
        "end_date": "2026-10-08",
        "daily": [
            "temperature_2m_mean",
            "temperature_2m_max",
            "temperature_2m_min",
            "precipitation_sum",
            "wind_speed_10m_max"
        ],
        "timezone": "Asia/Kolkata"
    }

    response = requests.get(url, params=params)
    weather_data = response.json()

    weather_df = pd.DataFrame({
        "date": weather_data["daily"]["time"],
        "temperature_mean": weather_data["daily"]["temperature_2m_mean"],
        "temperature_max": weather_data["daily"]["temperature_2m_max"],
        "temperature_min": weather_data["daily"]["temperature_2m_min"],
        "precipitation_mm": weather_data["daily"]["precipitation_sum"],
        "wind_speed_max": weather_data["daily"]["wind_speed_10m_max"]
    })

    weather_df["state_ut"] = row["state_ut"]
    weather_df["city"] = city

    all_weather_data.append(weather_df)

final_weather_df = pd.concat(all_weather_data, ignore_index=True)

print(final_weather_df.head())
print(final_weather_df.shape)

         date  temperature_mean  temperature_max  temperature_min  \
0  2026-07-01              31.9             34.9             29.7
1  2026-07-02              30.5             34.2             26.3
2  2026-07-03              30.3             33.2             26.8
3  2026-07-04              28.3             30.7             25.5
4  2026-07-05              29.8             33.1             25.7

   precipitation_mm  wind_speed_max        state_ut       city
0               0.4            25.2  Andhra Pradesh  Amaravati
1               3.1            27.2  Andhra Pradesh  Amaravati
2               1.4            25.5  Andhra Pradesh  Amaravati
3               5.1            23.6  Andhra Pradesh  Amaravati
4               0.7            21.7  Andhra Pradesh  Amaravati
(3600, 8)

In [22]:
# 1. Number of rows and columns
print(final_weather_df.shape)

# 2. Number of unique state/UT entries
print(final_weather_df["state_ut"].nunique())

# 3. Check the date range
print(final_weather_df["date"].min())
print(final_weather_df["date"].max())

# 4. Check missing values
print(final_weather_df.isnull().sum())

(3600, 8)
36
2026-07-01
2026-10-08
date                0
temperature_mean    0
temperature_max     0
temperature_min     0
precipitation_mm    0
wind_speed_max      0
state_ut            0
city                0
dtype: int64

In [23]:
print(final_weather_df.shape)

print(
    final_weather_df[
        final_weather_df["state_ut"].isin(
            ["Haryana", "Punjab", "Chandigarh"]
        )
    ][["state_ut", "city"]]
    .drop_duplicates()
    .sort_values("state_ut")
)

(3600, 8)
        state_ut        city
2900  Chandigarh  Chandigarh
700      Haryana  Chandigarh
1900      Punjab  Chandigarh

In [24]:
air_url = "https://air-quality-api.open-meteo.com/v1/air-quality"

air_params = {
    "latitude": latitude,
    "longitude": longitude,
    "start_date": "2026-07-09",
    "end_date": "2026-10-08",
    "hourly": [
      "pm2_5",
      "pm10",
      "carbon_monoxide",
      "nitrogen_dioxide",
      "sulphur_dioxide",
      "ozone"
  ],
    "timezone": "Asia/Kolkata"
}

air_response = requests.get(air_url,params = air_params)
air_data = air_response.json()

print(air_response.status_code)
print(air_response)

print(air_data.keys())

200
<Response [200]>
dict_keys(['latitude', 'longitude', 'generationtime_ms', 'utc_offset_seconds', 'timezone', 'timezone_abbreviation', 'elevation', 'hourly_units', 'hourly'])

In [25]:
print(air_data["hourly"].keys())
print(len(air_data["hourly"]["time"]))

print(air_data["hourly"]["time"][:5])
print(air_data["hourly"]["pm2_5"][:5])

dict_keys(['time', 'pm2_5', 'pm10', 'carbon_monoxide', 'nitrogen_dioxide', 'sulphur_dioxide', 'ozone'])
2208
['2026-07-09T00:00', '2026-07-09T01:00', '2026-07-09T02:00', '2026-07-09T03:00', '2026-07-09T04:00']
[14.0, 14.2, 14.3, 14.4, 14.6]

In [26]:
air_hourly_df = pd.DataFrame({
    "date": air_data["hourly"]["time"],
    "pm2_5": air_data["hourly"]["pm2_5"],
    "pm10": air_data["hourly"]["pm10"],
    "carbon_monoxide": air_data["hourly"]["carbon_monoxide"],
    "nitrogen_dioxide": air_data["hourly"]["nitrogen_dioxide"],
    "sulphur_dioxide": air_data["hourly"]["sulphur_dioxide"],
    "ozone": air_data["hourly"]["ozone"]
})

air_hourly_df.head()

,date,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone
0,2026-07-09T00:00,14.0,18.9,262.0,17.5,9.6,34.0
1,2026-07-09T01:00,14.2,18.8,268.0,17.4,8.5,31.0
2,2026-07-09T02:00,14.3,18.7,259.0,17.6,7.7,28.0
3,2026-07-09T03:00,14.4,18.5,218.0,18.7,7.6,23.0
4,2026-07-09T04:00,14.6,18.5,163.0,20.0,7.8,18.0

In [27]:
air_hourly_df = pd.DataFrame(air_data["hourly"])

print(air_hourly_df.columns.tolist())
print(air_hourly_df.head())
print(air_hourly_df.shape)

['time', 'pm2_5', 'pm10', 'carbon_monoxide', 'nitrogen_dioxide', 'sulphur_dioxide', 'ozone']
               time  pm2_5  pm10  carbon_monoxide  nitrogen_dioxide  \
0  2026-07-09T00:00   14.0  18.9            262.0              17.5
1  2026-07-09T01:00   14.2  18.8            268.0              17.4
2  2026-07-09T02:00   14.3  18.7            259.0              17.6
3  2026-07-09T03:00   14.4  18.5            218.0              18.7
4  2026-07-09T04:00   14.6  18.5            163.0              20.0

   sulphur_dioxide  ozone
0              9.6   34.0
1              8.5   31.0
2              7.7   28.0
3              7.6   23.0
4              7.8   18.0
(2208, 7)

In [28]:
air_hourly_df["date"] = pd.to_datetime(air_hourly_df["time"]).dt.date

print(air_hourly_df[["time","date"]].head())

               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09

In [29]:
pollutant_columns = [
    "pm2_5",
    "pm10",
    "carbon_monoxide",
    "nitrogen_dioxide",
    "sulphur_dioxide",
    "ozone"
]

air_daily_df = (
    air_hourly_df.groupby("date")[pollutant_columns].mean().reset_index()
)

print(air_daily_df.head())
print(air_daily_df.shape)

         date      pm2_5       pm10  carbon_monoxide  nitrogen_dioxide  \
0  2026-07-09  18.666667  25.729167       208.000000         13.370833
1  2026-07-10  18.825000  26.454167       252.625000         12.491667
2  2026-07-11  21.391667  35.216667       236.750000         12.000000
3  2026-07-12  18.687500  30.729167       190.291667          9.420833
4  2026-07-13  18.808333  32.687500       164.000000          9.112500

   sulphur_dioxide      ozone
0         9.208333  65.458333
1        10.687500  78.916667
2        10.162500  84.750000
3         7.966667  81.750000
4         5.233333  80.375000
(92, 7)

In [30]:
print(city_coord.iloc[-1][["state_ut","city","latitude","longitude"]])

state_ut     Puducherry
city         Puducherry
latitude       11.93381
longitude      79.82979
Name: 35, dtype: object

In [31]:
air_daily_df["state_ut"] = city_coord.iloc[-1]["state_ut"]
air_daily_df["city"] = city_coord.iloc[-1]["city"]

print(air_daily_df.head())

         date      pm2_5       pm10  carbon_monoxide  nitrogen_dioxide  \
0  2026-07-09  18.666667  25.729167       208.000000         13.370833
1  2026-07-10  18.825000  26.454167       252.625000         12.491667
2  2026-07-11  21.391667  35.216667       236.750000         12.000000
3  2026-07-12  18.687500  30.729167       190.291667          9.420833
4  2026-07-13  18.808333  32.687500       164.000000          9.112500

   sulphur_dioxide      ozone    state_ut        city
0         9.208333  65.458333  Puducherry  Puducherry
1        10.687500  78.916667  Puducherry  Puducherry
2        10.162500  84.750000  Puducherry  Puducherry
3         7.966667  81.750000  Puducherry  Puducherry
4         5.233333  80.375000  Puducherry  Puducherry

In [32]:
air_url = "https://air-quality-api.open-meteo.com/v1/air-quality"

all_air_data = []

air_response = requests.get(air_url, params=air_params)
air_response.raise_for_status()
air_data = air_response.json()

for index,row in city_coord.iterrows():
  city = row["city"]
  state_ut = row["state_ut"]
  latitude = row["latitude"]
  longitude = row["longitude"]

  air_params = {
    "latitude": latitude,
    "longitude": longitude,
    "start_date": "2026-07-09",
    "end_date": "2026-10-08",
    "hourly": [
      "pm2_5",
      "pm10",
      "carbon_monoxide",
      "nitrogen_dioxide",
      "sulphur_dioxide",
      "ozone"
  ],
    "timezone": "Asia/Kolkata"
  }

  air_hourly_df = pd.DataFrame(air_data["hourly"])
  print(city, air_hourly_df.shape)

  air_hourly_df["date"] = pd.to_datetime(
    air_hourly_df["time"]
).dt.date

  print(air_hourly_df[["time", "date"]].head())

  pollutant_columns = [
    "pm2_5",
    "pm10",
    "carbon_monoxide",
    "nitrogen_dioxide",
    "sulphur_dioxide",
    "ozone"
  ]

  air_daily_df = (
      air_hourly_df.groupby("date")[pollutant_columns].mean().reset_index()
  )

  air_daily_df["state_ut"] = state_ut
  air_daily_df["city"] = city

  all_air_data.append(air_daily_df)

final_air_df = pd.concat(all_air_data, ignore_index=True)

print(final_air_df.head())
print(final_air_df.shape)

Amaravati (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Itanagar (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Dispur (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Patna (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Raipur (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Panaji (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Gandhinagar (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Chandigarh (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Shimla (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Ranchi (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Bengaluru (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Thiruvananthapuram (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Bhopal (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Mumbai (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Imphal (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Shillong (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Aizawl (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Kohima (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Bhubaneswar (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Chandigarh (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Jaipur (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Gangtok (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Chennai (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Hyderabad (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Agartala (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Lucknow (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Dehradun (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Kolkata (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Port Blair (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Chandigarh (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Daman (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
New Delhi (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Srinagar (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Leh (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Kavaratti (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
Puducherry (2208, 7)
               time        date
0  2026-07-09T00:00  2026-07-09
1  2026-07-09T01:00  2026-07-09
2  2026-07-09T02:00  2026-07-09
3  2026-07-09T03:00  2026-07-09
4  2026-07-09T04:00  2026-07-09
         date      pm2_5       pm10  carbon_monoxide  nitrogen_dioxide  \
0  2026-07-09  18.666667  25.729167       208.000000         13.370833
1  2026-07-10  18.825000  26.454167       252.625000         12.491667
2  2026-07-11  21.391667  35.216667       236.750000         12.000000
3  2026-07-12  18.687500  30.729167       190.291667          9.420833
4  2026-07-13  18.808333  32.687500       164.000000          9.112500

   sulphur_dioxide      ozone        state_ut       city
0         9.208333  65.458333  Andhra Pradesh  Amaravati
1        10.687500  78.916667  Andhra Pradesh  Amaravati
2        10.162500  84.750000  Andhra Pradesh  Amaravati
3         7.966667  81.750000  Andhra Pradesh  Amaravati
4         5.233333  80.375000  Andhra Pradesh  Amaravati
(3312, 9)

In [33]:
print(final_air_df.shape)

print(
    final_air_df[
        final_air_df["state_ut"].isin(
            ["Haryana", "Punjab", "Chandigarh"]
        )
    ][["state_ut", "city"]]
    .drop_duplicates()
    .sort_values("state_ut")
)

(3312, 9)
        state_ut        city
2668  Chandigarh  Chandigarh
644      Haryana  Chandigarh
1748      Punjab  Chandigarh

In [34]:
all_air_data = []

pollutant_columns = [
    "pm2_5",
    "pm10",
    "carbon_monoxide",
    "nitrogen_dioxide",
    "sulphur_dioxide",
    "ozone"
]

for index, row in city_coord.iterrows():

    city = row["city"]
    state_ut = row["state_ut"]
    latitude = row["latitude"]
    longitude = row["longitude"]

    air_params = {
        "latitude": latitude,
        "longitude": longitude,
        "start_date": "2026-07-09",
        "end_date": "2026-10-08",
        "hourly": pollutant_columns,
        "timezone": "Asia/Kolkata"
    }

    # Request data for the current city
    air_response = requests.get(air_url, params=air_params)
    air_response.raise_for_status()
    air_data = air_response.json()

    # Convert hourly API data into a DataFrame
    air_hourly_df = pd.DataFrame(air_data["hourly"])

    # Extract the date from each timestamp
    air_hourly_df["date"] = pd.to_datetime(
        air_hourly_df["time"]
    ).dt.date

    # Calculate daily averages
    air_daily_df = (
        air_hourly_df
        .groupby("date")[pollutant_columns]
        .mean()
        .reset_index()
    )

    # Label the records with their location
    air_daily_df["state_ut"] = state_ut
    air_daily_df["city"] = city

    # Save this city's daily records
    all_air_data.append(air_daily_df)

    print(f"Collected {city}: {len(air_daily_df)} records")

# Outside the loop: combine all city DataFrames
final_air_df = pd.concat(all_air_data, ignore_index=True)

print(final_air_df.head())
print(final_air_df.shape)

Collected Amaravati: 92 records
Collected Itanagar: 92 records
Collected Dispur: 92 records
Collected Patna: 92 records
Collected Raipur: 92 records
Collected Panaji: 92 records
Collected Gandhinagar: 92 records
Collected Chandigarh: 92 records
Collected Shimla: 92 records
Collected Ranchi: 92 records
Collected Bengaluru: 92 records
Collected Thiruvananthapuram: 92 records
Collected Bhopal: 92 records
Collected Mumbai: 92 records
Collected Imphal: 92 records
Collected Shillong: 92 records
Collected Aizawl: 92 records
Collected Kohima: 92 records
Collected Bhubaneswar: 92 records
Collected Chandigarh: 92 records
Collected Jaipur: 92 records
Collected Gangtok: 92 records
Collected Chennai: 92 records
Collected Hyderabad: 92 records
Collected Agartala: 92 records
Collected Lucknow: 92 records
Collected Dehradun: 92 records
Collected Kolkata: 92 records
Collected Port Blair: 92 records
Collected Chandigarh: 92 records
Collected Daman: 92 records
Collected New Delhi: 92 records
Collected Srinagar: 92 records
Collected Leh: 92 records
Collected Kavaratti: 92 records
Collected Puducherry: 92 records
         date      pm2_5       pm10  carbon_monoxide  nitrogen_dioxide  \
0  2026-07-09  17.541667  24.645833       158.791667          9.570833
1  2026-07-10  27.925000  48.304167       223.583333         11.700000
2  2026-07-11  27.841667  48.350000       180.083333         12.916667
3  2026-07-12  25.958333  48.587500       189.041667         10.216667
4  2026-07-13  24.941667  45.975000       206.625000          9.054167

   sulphur_dioxide      ozone        state_ut       city
0         5.691667  58.416667  Andhra Pradesh  Amaravati
1         6.116667  55.250000  Andhra Pradesh  Amaravati
2         5.987500  53.291667  Andhra Pradesh  Amaravati
3         5.875000  57.750000  Andhra Pradesh  Amaravati
4         5.670833  62.000000  Andhra Pradesh  Amaravati
(3312, 9)

In [35]:
print(final_air_df.shape)
print(final_air_df["city"].nunique())

(3312, 9)
34

In [36]:
print(final_air_df["state_ut"].nunique())
print(final_air_df["city"].value_counts().head())

36
city
Chandigarh    276
Amaravati      92
Itanagar       92
Dispur         92
Raipur         92
Name: count, dtype: int64

In [37]:
final_weather_df["date"] = pd.to_datetime(final_weather_df["date"])
final_air_df["date"] = pd.to_datetime(final_air_df["date"])

final_df = pd.merge(
    final_weather_df,
    final_air_df,
    on = ["state_ut","city","date"],
    how = "inner"
  )

print(final_df.head())
print(final_df.shape)

        date  temperature_mean  temperature_max  temperature_min  \
0 2026-07-09              31.3             35.4             28.3
1 2026-07-10              32.2             36.3             27.0
2 2026-07-11              32.6             35.7             29.8
3 2026-07-12              32.7             36.3             29.8
4 2026-07-13              33.2             36.7             30.7

   precipitation_mm  wind_speed_max        state_ut       city      pm2_5  \
0               2.0            19.0  Andhra Pradesh  Amaravati  17.541667
1               3.0            21.4  Andhra Pradesh  Amaravati  27.925000
2               0.1            21.4  Andhra Pradesh  Amaravati  27.841667
3               0.0            22.7  Andhra Pradesh  Amaravati  25.958333
4               0.0            25.1  Andhra Pradesh  Amaravati  24.941667

        pm10  carbon_monoxide  nitrogen_dioxide  sulphur_dioxide      ozone
0  24.645833       158.791667          9.570833         5.691667  58.416667
1  48.304167       223.583333         11.700000         6.116667  55.250000
2  48.350000       180.083333         12.916667         5.987500  53.291667
3  48.587500       189.041667         10.216667         5.875000  57.750000
4  45.975000       206.625000          9.054167         5.670833  62.000000
(3312, 14)

In [38]:
# 1. Check rows and columns
print("Dataset shape:", final_df.shape)

# 2. Check missing values
print("\nMissing values:")
print(final_df.isnull().sum())

# 3. Check duplicate records
print("\nDuplicate records:",
      final_df.duplicated(
          subset=["state_ut", "city", "date"]
      ).sum())

# 4. Check the date range
print("\nDate range:")
print(final_df["date"].min())
print(final_df["date"].max())

# 5. Check how many state/UT-city combinations exist
print("\nUnique locations:",
      final_df[["state_ut", "city"]].drop_duplicates().shape[0])

Dataset shape: (3312, 14)

Missing values:
date                0
temperature_mean    0
temperature_max     0
temperature_min     0
precipitation_mm    0
wind_speed_max      0
state_ut            0
city                0
pm2_5               0
pm10                0
carbon_monoxide     0
nitrogen_dioxide    0
sulphur_dioxide     0
ozone               0
dtype: int64

Duplicate records: 0

Date range:
2026-07-09 00:00:00
2026-10-08 00:00:00

Unique locations: 36

In [39]:
for location in locations:
    if location["state_ut"] == "Haryana":
        location["city"] = "Gurugram"

    elif location["state_ut"] == "Punjab":
        location["city"] = "Amritsar"

In [40]:
for location in locations:
    if location["state_ut"] in ["Haryana", "Punjab", "Chandigarh"]:
        print(location)

{'state_ut': 'Haryana', 'city': 'Gurugram'}
{'state_ut': 'Punjab', 'city': 'Amritsar'}
{'state_ut': 'Chandigarh', 'city': 'Chandigarh'}

In [41]:
final_weather_df["date"] = pd.to_datetime(final_weather_df["date"])
final_air_df["date"] = pd.to_datetime(final_air_df["date"])

final_df = pd.merge(
    final_weather_df,
    final_air_df,
    on = ["state_ut","city","date"],
    how = "inner"
  )

print(final_df.head())
print(final_df.shape)

        date  temperature_mean  temperature_max  temperature_min  \
0 2026-07-09              31.3             35.4             28.3
1 2026-07-10              32.2             36.3             27.0
2 2026-07-11              32.6             35.7             29.8
3 2026-07-12              32.7             36.3             29.8
4 2026-07-13              33.2             36.7             30.7

   precipitation_mm  wind_speed_max        state_ut       city      pm2_5  \
0               2.0            19.0  Andhra Pradesh  Amaravati  17.541667
1               3.0            21.4  Andhra Pradesh  Amaravati  27.925000
2               0.1            21.4  Andhra Pradesh  Amaravati  27.841667
3               0.0            22.7  Andhra Pradesh  Amaravati  25.958333
4               0.0            25.1  Andhra Pradesh  Amaravati  24.941667

        pm10  carbon_monoxide  nitrogen_dioxide  sulphur_dioxide      ozone
0  24.645833       158.791667          9.570833         5.691667  58.416667
1  48.304167       223.583333         11.700000         6.116667  55.250000
2  48.350000       180.083333         12.916667         5.987500  53.291667
3  48.587500       189.041667         10.216667         5.875000  57.750000
4  45.975000       206.625000          9.054167         5.670833  62.000000
(3312, 14)

In [42]:
print(
    final_df[
        final_df["state_ut"].isin(
            ["Haryana", "Punjab", "Chandigarh"]
        )
    ][["state_ut", "city"]]
    .drop_duplicates()
    .sort_values("state_ut")
    .to_string(index=False)
)

print("\nUnique city names:", final_df["city"].nunique())
print("Unique state/UT-city pairs:",
      final_df[["state_ut", "city"]].drop_duplicates().shape[0])

  state_ut       city
Chandigarh Chandigarh
   Haryana Chandigarh
    Punjab Chandigarh

Unique city names: 34
Unique state/UT-city pairs: 36

In [43]:
for location in locations:
    if location["state_ut"] == "Haryana":
        location["city"] = "Gurugram"

    elif location["state_ut"] == "Punjab":
        location["city"] = "Amritsar"

In [44]:
for location in locations:
    if location["state_ut"] in ["Haryana", "Punjab", "Chandigarh"]:
        print(location)

{'state_ut': 'Haryana', 'city': 'Gurugram'}
{'state_ut': 'Punjab', 'city': 'Amritsar'}
{'state_ut': 'Chandigarh', 'city': 'Chandigarh'}

In [45]:
final_weather_df["date"] = pd.to_datetime(final_weather_df["date"])
final_air_df["date"] = pd.to_datetime(final_air_df["date"])

final_df = pd.merge(
    final_weather_df,
    final_air_df,
    on=["state_ut", "city", "date"],
    how="inner"
)

print(final_df.shape)
print(final_df["city"].nunique())
print(final_df[["state_ut", "city"]].drop_duplicates().shape[0])

(3312, 14)
34
36

In [46]:
print("Shape:", final_df.shape)

print("Unique city names:", final_df["city"].nunique())

print("Unique state/UT-city pairs:",
      final_df[["state_ut", "city"]].drop_duplicates().shape[0])

print("Missing values:", final_df.isnull().sum().sum())

print("Duplicate records:",
      final_df.duplicated(
          subset=["state_ut", "city", "date"]
      ).sum())

Shape: (3312, 14)
Unique city names: 34
Unique state/UT-city pairs: 36
Missing values: 0
Duplicate records: 0

In [47]:
final_df.to_csv(
    "india_weather_air_quality_2026.csv",
    index=False
)

In [48]:
from google.colab import files

files.download("india_weather_air_quality_2026.csv")